In [50]:
c ** 2

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [47]:
c // 3

array([[0, 0, 1],
       [1, 1, 1]])

In [46]:
c % 3

array([[1, 2, 0],
       [0, 1, 2]])

In [45]:
c / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])

In [44]:

c * 2


array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [43]:
c - 2

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [42]:
c + 4

array([[5, 6, 7],
       [7, 8, 9]])

In [41]:
c = np.array([[1,2,3], [3,4,5]])
c

array([[1, 2, 3],
       [3, 4, 5]])

In [40]:
multidimensional[(multidimensional > 45 )  & (multidimensional == 65)]

array([65, 65], dtype=int32)

In [38]:
multidimensional[(multidimensional > 60) |  (multidimensional < 15)]

array([89, 14, 67, 65,  3, 97, 74, 12, 65,  8, 94,  6,  2,  7, 91, 83, 66,
       81], dtype=int32)

In [37]:
multidimensional[multidimensional > 45]

array([53, 89, 48, 67, 65, 97, 74, 51, 65, 94, 55, 91, 83, 66, 81],
      dtype=int32)

In [36]:
multidimensional > 30

array([[[ True,  True,  True, False,  True],
        [False,  True,  True,  True, False],
        [ True,  True, False,  True,  True]],

       [[False,  True,  True, False,  True],
        [ True, False, False, False, False],
        [ True,  True,  True, False,  True]]])

In [35]:
multidimensional[0][:][0]

array([38, 53, 89, 29, 36], dtype=int32)

In [34]:
multidimensional[0, 1, :]

array([14, 48, 67, 65,  3], dtype=int32)

In [33]:
multidimensional[1,2,4]

np.int32(81)

In [32]:
multidimensional = np.random.randint(0,100, (2,3,5))
multidimensional

array([[[38, 53, 89, 29, 36],
        [14, 48, 67, 65,  3],
        [97, 74, 12, 51, 65]],

       [[ 8, 94, 32, 20, 42],
        [55,  6,  2,  7, 19],
        [91, 83, 66, 17, 81]]], dtype=int32)

In [31]:
unidimensional = np.random.random_sample(15)
unidimensional

#Si queremos acceder al primer elemento de nuestro array
unidimensional[0] # Output: 0.11004850610895134

#Si queremos acceder a los tres últimos elementos
unidimensional[-3:] # Output: array([0.25789705, 0.15254418, 0.64145759])

#Si queremos acceder a los tres últimos elementos
unidimensional[-3:] # Output: array([0.25789705, 0.15254418, 0.64145759])

# Si queremos seleccionar el tercer y cuarto elemento
unidimensional[3:5] # Output: array([0.98074997, 0.47281141])

# Los elementos desde el inicio hasta el 10 en saltos de dos en dos
unidimensional[:11:2] # Output: array([0.11004851, 0.25918084, 0.47281141, 0.73482103, 0.9731047 , 0.64327416])


array([0.51466029, 0.52455035, 0.94067676, 0.56311246, 0.9829917 ,
       0.70557827])

In [28]:
lst = [12,20,3,45,6,23,81,93]
lst[::2]

[12, 3, 6, 81]

In [27]:
lst = [12,20,3,45,6,23,81,93]
lst[:4]


[12, 20, 3, 45]

In [26]:
lst = [12,20,3,45,6,23,81,93]
lst[3:6]

[45, 6, 23]

In [25]:
lst = [12,20,3,45,6,23,81,93]
lst[3:]

[45, 6, 23, 81, 93]

In [23]:
a.ndim

3

In [22]:
a.shape

(2, 3, 4)

In [21]:
a.ndim
a.shape
a.dtype

dtype('int32')

In [20]:
type(a)

numpy.ndarray

In [19]:
a3 = np.random.random_sample((2, 3, 4))
a3

array([[[0.0862028 , 0.2081522 , 0.08429865, 0.89709114],
        [0.39919554, 0.07538749, 0.12171931, 0.72423088],
        [0.75011986, 0.39259319, 0.96008344, 0.10762881]],

       [[0.76335624, 0.16690703, 0.90485374, 0.82459897],
        [0.6572694 , 0.39211889, 0.23228982, 0.61419994],
        [0.78484509, 0.20560003, 0.39922125, 0.85296755]]])

In [18]:
a2 = np.random.rand(2, 3, 4)
a2

array([[[0.29471751, 0.89681696, 0.59979611, 0.37206323],
        [0.96473736, 0.78518274, 0.27421098, 0.33237621],
        [0.06177746, 0.31831187, 0.01018457, 0.15544991]],

       [[0.43083424, 0.994873  , 0.54759639, 0.87262161],
        [0.98697871, 0.66691494, 0.46709264, 0.51304117],
        [0.80096831, 0.72945462, 0.48526051, 0.48092061]]])

In [17]:
a = np.random.randint(0, 50, (2, 3, 4))
a

array([[[47, 23, 35,  1],
        [16, 21, 18, 11],
        [ 1,  3, 39, 46]],

       [[37,  3,  9, 24],
        [ 6,  8, 41,  6],
        [28, 14, 37,  4]]], dtype=int32)

In [14]:
iden = np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
unos = np.ones((3, 5), dtype=int)
unos

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
ceros3 = np.zeros((3, 5 ,4), dtype=int )
ceros3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [11]:
lista = [[1, 2, 3, 4, 5  ], [6, 7, 8, 9, 10]]
array = np.array(lista)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
eye4 = np.eye(4, k = -1)
eye4

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [8]:
eye3 = np.eye(4, k = 2)
eye3


array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
import numpy as np


In [5]:
eye2 = np.eye(4, k = 1)
eye2


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [6]:
eye1 = np.eye(4)
eye1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# resultado = 3 + 4
# print("el resultado de la suma es: ", resultado)
