# Operaciones de comparación


In [2]:
d = np.random.randint(1,20, (4,5))
d

array([[15, 19,  3,  4, 17],
       [ 2, 19, 12, 13,  4],
       [ 3, 15,  9, 12,  4],
       [12,  5,  4, 17,  6]], dtype=int32)

In [ ]:
np.any(d > 10)



np.True_

In [5]:
np.any(d > 20)

np.False_

In [6]:
np.any(d > 10, axis = 0)


array([ True,  True,  True,  True,  True])

In [7]:
np.any(d < 2 , axis = 1 )


array([False, False, False, False])

In [8]:
np.all(d > 10)

np.False_

In [9]:
np.all(d > 10, axis = 0)

array([False, False, False, False, False])

In [10]:
np.all(d > 10, axis = 1)

array([False, False, False, False])

In [11]:
np.any(d < 2 , axis = 1 )

array([False, False, False, False])

In [1]:
import numpy as np