# Operaciones Aricmeticas


In [7]:
    d = np.random.randint(1,20, (4,5))

    d

array([[ 8, 14,  5, 15,  2],
       [ 6, 16,  7,  1,  2],
       [14,  9, 19, 18,  6],
       [18,  8,  4,  8, 13]], dtype=int32)

In [8]:
np.min(d)

np.int32(1)

In [9]:
np.min(d, axis = 0)

array([6, 8, 4, 1, 2], dtype=int32)

In [10]:
np.min(d, axis = 1)

array([2, 1, 6, 4], dtype=int32)

In [11]:
np.max(d)

np.int32(19)

In [12]:
np.max(d, axis = 0)

array([18, 16, 19, 18, 13], dtype=int32)

In [13]:

np.max(d, axis = 1)

array([15, 16, 19, 18], dtype=int32)

In [14]:
np.sum(d)

np.int64(193)

In [15]:
np.sum(d, axis = 0)

array([46, 47, 35, 42, 23])

In [19]:
np.sum(d, axis = 1)

array([44, 32, 66, 51])

In [20]:
np.cumsum(d)

array([  8,  22,  27,  42,  44,  50,  66,  73,  74,  76,  90,  99, 118,
       136, 142, 160, 168, 172, 180, 193])

In [21]:
np.cumsum(d, axis = 0)


array([[ 8, 14,  5, 15,  2],
       [14, 30, 12, 16,  4],
       [28, 39, 31, 34, 10],
       [46, 47, 35, 42, 23]])

In [22]:
np.cumsum(d, axis = 1)

array([[ 8, 22, 27, 42, 44],
       [ 6, 22, 29, 30, 32],
       [14, 23, 42, 60, 66],
       [18, 26, 30, 38, 51]])

In [23]:
np.cumprod(d)

array([                 8,                112,                560,
                     8400,              16800,             100800,
                  1612800,           11289600,           11289600,
                 22579200,          316108800,         2844979200,
              54054604800,       972982886400,      5837897318400,
          105082151731200,    840657213849600,   3362628855398400,
        26901030843187200, 349713400961433600])

In [24]:
np.sqrt(d)

array([[2.82842712, 3.74165739, 2.23606798, 3.87298335, 1.41421356],
       [2.44948974, 4.        , 2.64575131, 1.        , 1.41421356],
       [3.74165739, 3.        , 4.35889894, 4.24264069, 2.44948974],
       [4.24264069, 2.82842712, 2.        , 2.82842712, 3.60555128]])

In [25]:
np.exp(d)

array([[2.98095799e+03, 1.20260428e+06, 1.48413159e+02, 3.26901737e+06,
        7.38905610e+00],
       [4.03428793e+02, 8.88611052e+06, 1.09663316e+03, 2.71828183e+00,
        7.38905610e+00],
       [1.20260428e+06, 8.10308393e+03, 1.78482301e+08, 6.56599691e+07,
        4.03428793e+02],
       [6.56599691e+07, 2.98095799e+03, 5.45981500e+01, 2.98095799e+03,
        4.42413392e+05]])

In [4]:
import numpy as np