### Operaciones de comparación


In [27]:
np.var(d, axis = 1)

array([46.56, 16.56, 39.76, 24.24])

In [26]:
np.var(d, axis = 0)


array([32.1875, 13.    , 31.25  , 17.5   , 44.25  ])

In [23]:
np.std(d, axis = 1)

array([6.82348884, 4.06939799, 6.30555311, 4.92341345])

In [22]:
np.std(d, axis = 0)

array([5.67340286, 3.60555128, 5.59016994, 4.18330013, 6.65206735])

In [21]:
np.std(d)

np.float64(6.048760203545847)

In [20]:
media_columnas = np.mean(d, axis = 0)
media_columnas

array([ 6.25,  7.  , 10.5 ,  8.  , 14.5 ])

In [19]:
media_filas = np.mean(d, axis = 1)
media_filas

array([10.2,  7.2,  7.2, 12.4])

In [18]:
media = np.mean(d)
media


np.float64(9.25)

In [17]:
d = np.random.randint(1,20, (4,5))
d

array([[ 2,  2, 14, 15, 18],
       [ 3, 12, 12,  6,  3],
       [ 4,  8,  1,  4, 19],
       [16,  6, 15,  7, 18]], dtype=int32)

### Operaciones de estadistica

In [16]:
y = a // b
y

C:\Users\Gonzalo Arranz\AppData\Local\Temp\ipykernel_21768\3868353900.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  y = a // b


array([[[inf,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [inf,  0.,  0.,  0.]]])

In [14]:
a // b

C:\Users\Gonzalo Arranz\AppData\Local\Temp\ipykernel_21768\3774276598.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a // b


array([[[inf,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [inf,  0.,  0.,  0.]]])

In [13]:
np.divide(a, b)

C:\Users\Gonzalo Arranz\AppData\Local\Temp\ipykernel_21768\3737392904.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a, b)


array([[[       inf, 0.25      , 0.11111111, 0.33333333],
        [0.14285714, 0.25      , 0.33333333, 0.2       ],
        [0.25      , 0.33333333, 0.16666667, 0.14285714]],

       [[0.16666667, 0.2       , 0.16666667, 0.5       ],
        [0.33333333, 0.25      , 0.33333333, 0.11111111],
        [       inf, 0.14285714, 0.14285714, 0.2       ]]])

In [12]:
a / b

C:\Users\Gonzalo Arranz\AppData\Local\Temp\ipykernel_21768\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([[[       inf, 0.25      , 0.11111111, 0.33333333],
        [0.14285714, 0.25      , 0.33333333, 0.2       ],
        [0.25      , 0.33333333, 0.16666667, 0.14285714]],

       [[0.16666667, 0.2       , 0.16666667, 0.5       ],
        [0.33333333, 0.25      , 0.33333333, 0.11111111],
        [       inf, 0.14285714, 0.14285714, 0.2       ]]])

In [11]:
np.multiply(a, b)

array([[[0., 4., 9., 3.],
        [7., 4., 3., 5.],
        [4., 3., 6., 7.]],

       [[6., 5., 6., 2.],
        [3., 4., 3., 9.],
        [0., 7., 7., 5.]]])

In [10]:
a *b

array([[[0., 4., 9., 3.],
        [7., 4., 3., 5.],
        [4., 3., 6., 7.]],

       [[6., 5., 6., 2.],
        [3., 4., 3., 9.],
        [0., 7., 7., 5.]]])

In [9]:
np.subtract(a, b)

array([[[ 1., -3., -8., -2.],
        [-6., -3., -2., -4.],
        [-3., -2., -5., -6.]],

       [[-5., -4., -5., -1.],
        [-2., -3., -2., -8.],
        [ 1., -6., -6., -4.]]])

In [8]:
a - b

array([[[ 1., -3., -8., -2.],
        [-6., -3., -2., -4.],
        [-3., -2., -5., -6.]],

       [[-5., -4., -5., -1.],
        [-2., -3., -2., -8.],
        [ 1., -6., -6., -4.]]])

In [6]:
suma.astype(int)

array([[[ 1,  5, 10,  4],
        [ 8,  5,  4,  6],
        [ 5,  4,  7,  8]],

       [[ 7,  6,  7,  3],
        [ 4,  5,  4, 10],
        [ 1,  8,  8,  6]]])

In [5]:
suma = np.add(a ,b)
suma

array([[[ 1.,  5., 10.,  4.],
        [ 8.,  5.,  4.,  6.],
        [ 5.,  4.,  7.,  8.]],

       [[ 7.,  6.,  7.,  3.],
        [ 4.,  5.,  4., 10.],
        [ 1.,  8.,  8.,  6.]]])

In [4]:
a + b

array([[[ 1.,  5., 10.,  4.],
        [ 8.,  5.,  4.,  6.],
        [ 5.,  4.,  7.,  8.]],

       [[ 7.,  6.,  7.,  3.],
        [ 4.,  5.,  4., 10.],
        [ 1.,  8.,  8.,  6.]]])

In [3]:
b

array([[[0, 4, 9, 3],
        [7, 4, 3, 5],
        [4, 3, 6, 7]],

       [[6, 5, 6, 2],
        [3, 4, 3, 9],
        [0, 7, 7, 5]]], dtype=int32)

In [2]:
a = np.ones((2,3,4))
b = np.random.randint(0,10, (2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Operaciones entre arrays

In [1]:
import numpy as np